/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HospitalPatientsApp;

/**
 *
 * @author Mohiuddin Khan Rafi(22128271)
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuIconJpnl = new javax.swing.JPanel();
        menuTitleLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();
        menuPatientsBtn = new javax.swing.JButton();
        menuEmpBtn = new javax.swing.JButton();
        stockBtn = new javax.swing.JButton();
        optionLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 650));

        menuIconJpnl.setBackground(new java.awt.Color(255, 0, 0));

        menuTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        menuTitleLbl.setText("U.N Field Hospital Unit");

        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/MLogo.png"))); // NOI18N

        javax.swing.GroupLayout menuIconJpnlLayout = new javax.swing.GroupLayout(menuIconJpnl);
        menuIconJpnl.setLayout(menuIconJpnlLayout);
        menuIconJpnlLayout.setHorizontalGroup(
            menuIconJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuIconJpnlLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(menuTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuIconJpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconLbl)
                .addGap(52, 52, 52))
        );
        menuIconJpnlLayout.setVerticalGroup(
            menuIconJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuIconJpnlLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(menuTitleLbl)
                .addGap(40, 40, 40)
                .addComponent(iconLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPatientsBtn.setBackground(new java.awt.Color(255, 0, 0));
        menuPatientsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuPatientsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/patients.png"))); // NOI18N
        menuPatientsBtn.setText("Patient Registraion From");
        menuPatientsBtn.setBorderPainted(false);
        menuPatientsBtn.setFocusPainted(false);
        menuPatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientsBtnActionPerformed(evt);
            }
        });

        menuEmpBtn.setBackground(new java.awt.Color(255, 0, 0));
        menuEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/employees.png"))); // NOI18N
        menuEmpBtn.setText("Employee Details");
        menuEmpBtn.setBorderPainted(false);
        menuEmpBtn.setFocusPainted(false);

        stockBtn.setBackground(new java.awt.Color(255, 0, 0));
        stockBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stockBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/stocks.png"))); // NOI18N
        stockBtn.setText("Stock Table");
        stockBtn.setBorderPainted(false);
        stockBtn.setFocusPainted(false);

        optionLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        optionLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/select.png"))); // NOI18N
        optionLbl.setText("Select one to procceed");
        optionLbl.setAlignmentX(50.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuIconJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuPatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(optionLbl)))
                .addGap(0, 84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuIconJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(optionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(menuPatientsBtn)
                .addGap(47, 47, 47)
                .addComponent(menuEmpBtn)
                .addGap(44, 44, 44)
                .addComponent(stockBtn)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientsBtnActionPerformed
        // TODO add your handling code here:
        PatientsGUI p = new PatientsGUI();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPatientsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLbl;
    private javax.swing.JButton menuEmpBtn;
    private javax.swing.JPanel menuIconJpnl;
    private javax.swing.JButton menuPatientsBtn;
    private javax.swing.JLabel menuTitleLbl;
    private javax.swing.JLabel optionLbl;
    private javax.swing.JButton stockBtn;
    // End of variables declaration//GEN-END:variables
}
