/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HospitalPatientsApp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohiuddin Khan Rafi(22128271)
 */
public class PatientsGUI extends javax.swing.JFrame {

    private ArrayList<Patients> patients;

    /**
     * Creates new form PatientsGUI
     */
    public PatientsGUI() {
        initComponents();
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
        patients = new ArrayList<>();
        read();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpatientsJpan = new javax.swing.JPanel();
        formJpan = new javax.swing.JPanel();
        formTitleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        guardNamLbl = new javax.swing.JLabel();
        guardNamTf = new javax.swing.JTextField();
        ppsnLbl = new javax.swing.JLabel();
        ppsnTf = new javax.swing.JTextField();
        symptomsLbl = new javax.swing.JLabel();
        symptomsTf = new javax.swing.JTextField();
        symDurationLbl = new javax.swing.JLabel();
        symDurationTf = new javax.swing.JTextField();
        injurTypeLbl = new javax.swing.JLabel();
        injurTypeTf = new javax.swing.JTextField();
        bloodPLbl = new javax.swing.JLabel();
        bloodPTf = new javax.swing.JTextField();
        operationLbl = new javax.swing.JLabel();
        operationTf = new javax.swing.JTextField();
        concentLbl = new javax.swing.JLabel();
        concentTf = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        nameTf = new javax.swing.JTextField();
        searchAndRemoveAlertLbl = new javax.swing.JLabel();
        ordinaryPatientsRb = new javax.swing.JRadioButton();
        pTypeLbl = new javax.swing.JLabel();
        criticalPatientsRb = new javax.swing.JRadioButton();
        injuredPatientsRb = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        menuBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Registration Form");
        setMinimumSize(new java.awt.Dimension(800, 660));
        setPreferredSize(new java.awt.Dimension(800, 660));

        bgpatientsJpan.setBackground(new java.awt.Color(255, 255, 255));

        formJpan.setBackground(new java.awt.Color(255, 0, 0));

        formTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/patients.png"))); // NOI18N
        formTitleLbl.setText("Patient Registration Form");

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLbl.setText("Name:");

        ageLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLbl.setText("Age:");

        ageTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        guardNamLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardNamLbl.setText("Guardian Name:");

        guardNamTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ppsnLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ppsnLbl.setText("PPSN:");

        ppsnTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        symptomsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        symptomsLbl.setText("Symptoms:");

        symptomsTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        symDurationLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        symDurationLbl.setText("Symptom Duration:");

        symDurationTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        injurTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        injurTypeLbl.setText("Injury Type:");

        injurTypeTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        bloodPLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bloodPLbl.setText("Blood Pressure:");

        bloodPTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        operationLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        operationLbl.setText("Operation:");

        operationTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        concentLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        concentLbl.setText("Concent:");

        concentTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        clearBtn.setBackground(new java.awt.Color(0, 0, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setFocusable(false);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nameTf.setMinimumSize(new java.awt.Dimension(368, 24));
        nameTf.setPreferredSize(new java.awt.Dimension(368, 24));

        searchAndRemoveAlertLbl.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        searchAndRemoveAlertLbl.setForeground(new java.awt.Color(255, 255, 255));
        searchAndRemoveAlertLbl.setText("Put PPSN to search or remove patients");

        javax.swing.GroupLayout formJpanLayout = new javax.swing.GroupLayout(formJpan);
        formJpan.setLayout(formJpanLayout);
        formJpanLayout.setHorizontalGroup(
            formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formJpanLayout.createSequentialGroup()
                .addGroup(formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formJpanLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(formTitleLbl)
                        .addGap(90, 90, 90)
                        .addComponent(clearBtn))
                    .addGroup(formJpanLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLbl)
                                .addComponent(ageLbl)
                                .addComponent(guardNamLbl)
                                .addComponent(guardNamTf)
                                .addComponent(ppsnLbl)
                                .addComponent(symptomsLbl)
                                .addComponent(symptomsTf)
                                .addComponent(symDurationLbl)
                                .addComponent(symDurationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(injurTypeLbl)
                                .addComponent(injurTypeTf)
                                .addComponent(bloodPLbl)
                                .addComponent(bloodPTf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(operationLbl)
                                .addComponent(operationTf)
                                .addComponent(concentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(concentTf)
                                .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formJpanLayout.createSequentialGroup()
                                .addComponent(ppsnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchAndRemoveAlertLbl)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        formJpanLayout.setVerticalGroup(
            formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formJpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formTitleLbl)
                    .addComponent(clearBtn))
                .addGap(18, 18, 18)
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(ageLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardNamLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardNamTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ppsnLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppsnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAndRemoveAlertLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symptomsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symptomsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symDurationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symDurationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(injurTypeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(injurTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bloodPLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bloodPTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(concentLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(concentTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ordinaryPatientsRb.setBackground(new java.awt.Color(255, 0, 0));
        ordinaryPatientsRb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ordinaryPatientsRb.setText("Ordinary Patient");
        ordinaryPatientsRb.setFocusable(false);
        ordinaryPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryPatientsRbActionPerformed(evt);
            }
        });

        pTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pTypeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/pType.png"))); // NOI18N
        pTypeLbl.setText("Patient Type:");

        criticalPatientsRb.setBackground(new java.awt.Color(255, 0, 0));
        criticalPatientsRb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        criticalPatientsRb.setText("Critical Patient");
        criticalPatientsRb.setFocusable(false);
        criticalPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criticalPatientsRbActionPerformed(evt);
            }
        });

        injuredPatientsRb.setBackground(new java.awt.Color(255, 0, 0));
        injuredPatientsRb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        injuredPatientsRb.setText("Injured Patient");
        injuredPatientsRb.setFocusable(false);
        injuredPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuredPatientsRbActionPerformed(evt);
            }
        });

        menuBtn.setBackground(new java.awt.Color(0, 0, 0));
        menuBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/menu.png"))); // NOI18N
        menuBtn.setText("Menu");
        menuBtn.setFocusable(false);
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        displayBtn.setBackground(new java.awt.Color(0, 0, 0));
        displayBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(255, 255, 255));
        displayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/show.png"))); // NOI18N
        displayBtn.setText("Show Patient");
        displayBtn.setFocusable(false);
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/add.png"))); // NOI18N
        addBtn.setText("Add Patient");
        addBtn.setFocusable(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/search.png"))); // NOI18N
        searchBtn.setText("Search Patient");
        searchBtn.setFocusable(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(0, 0, 0));
        removeBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalPatientsApp/remove.png"))); // NOI18N
        removeBtn.setText("Remove Patient");
        removeBtn.setFocusable(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgpatientsJpanLayout = new javax.swing.GroupLayout(bgpatientsJpan);
        bgpatientsJpan.setLayout(bgpatientsJpanLayout);
        bgpatientsJpanLayout.setHorizontalGroup(
            bgpatientsJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpatientsJpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgpatientsJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(bgpatientsJpanLayout.createSequentialGroup()
                        .addGroup(bgpatientsJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criticalPatientsRb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(injuredPatientsRb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordinaryPatientsRb)
                            .addComponent(pTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn)
                            .addComponent(menuBtn)
                            .addComponent(displayBtn)
                            .addComponent(removeBtn)
                            .addComponent(searchBtn))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formJpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgpatientsJpanLayout.setVerticalGroup(
            bgpatientsJpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formJpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgpatientsJpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBtn)
                .addGap(20, 20, 20)
                .addComponent(pTypeLbl)
                .addGap(18, 18, 18)
                .addComponent(ordinaryPatientsRb)
                .addGap(18, 18, 18)
                .addComponent(injuredPatientsRb)
                .addGap(18, 18, 18)
                .addComponent(criticalPatientsRb)
                .addGap(44, 44, 44)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(displayBtn)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpatientsJpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpatientsJpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(true);
        symptomsTf.setVisible(true);
        symDurationLbl.setVisible(true);
        symDurationTf.setVisible(true);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
    }//GEN-LAST:event_ordinaryPatientsRbActionPerformed

    private void injuredPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuredPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(true);
        injurTypeTf.setVisible(true);
        bloodPLbl.setVisible(true);
        bloodPTf.setVisible(true);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
    }//GEN-LAST:event_injuredPatientsRbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (ordinaryPatientsRb.isSelected()) {
            //declare and create a new manager object m
            OrdinaryPatients o = new OrdinaryPatients();

            o.setName(nameTf.getText());
            o.setAge(ageTf.getText());
            o.setGuardNam(guardNamTf.getText());
            o.setPpsn(ppsnTf.getText());
            o.setSymptoms(symptomsTf.getText());
            o.setSymDuration(symDurationTf.getText());
            patients.add(o);

        } else if (injuredPatientsRb.isSelected()) {

            InjuredPatients i = new InjuredPatients();
            i.setName(nameTf.getText());
            i.setAge(ageTf.getText());
            i.setGuardNam(guardNamTf.getText());
            i.setPpsn(ppsnTf.getText());
            i.setInjurType(injurTypeTf.getText());
            i.setBloodP(bloodPTf.getText());
            //add object of arraylist
            patients.add(i);

        } else if (criticalPatientsRb.isSelected()) {

            CriticalPatients c = new CriticalPatients();
            c.setName(nameTf.getText());
            c.setAge(ageTf.getText());
            c.setGuardNam(guardNamTf.getText());
            c.setPpsn(ppsnTf.getText());
            c.setOperation(operationTf.getText());
            c.setConcent(concentTf.getText());

            patients.add(c);
        }
        clearFields();
        save();
    }//GEN-LAST:event_addBtnActionPerformed

    private void criticalPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criticalPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(true);
        operationTf.setVisible(true);
        concentLbl.setVisible(true);
        concentTf.setVisible(true);
    }//GEN-LAST:event_criticalPatientsRbActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient details in the system");
        } else {
            for (int i = 0; i < patients.size(); i++) {
                JOptionPane.showMessageDialog(null, patients.get(i).getDetails());

            }
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient to search");
        } else {
            String SearchTerm = ppsnTf.getText();

            for (Patients p : patients) {
                if (p.getPpsn().equalsIgnoreCase(SearchTerm)) {
                    JOptionPane.showMessageDialog(null, p.getDetails());
                }

            }

        }
        clearFields();
    }//GEN-LAST:event_searchBtnActionPerformed
    private void clearFields() {
        nameTf.setText(" ");
        ageTf.setText(" ");
        guardNamTf.setText(" ");
        ppsnTf.setText(" ");
        symptomsTf.setText(" ");
        symDurationTf.setText(" ");
        injurTypeTf.setText(" ");
        bloodPTf.setText(" ");
        operationTf.setText(" ");
        concentTf.setText(" ");

    }

    private void save() {
        //declare objects
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            //create objects
            f = new File("details.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);

            //use objects
            oStream.writeObject(patients);
        } catch (IOException e) {
            System.out.println("Error:" + e);
        }
    }

    private void read() {
        //declare objects
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            //create objects
            f = new File("details.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);

            //use objects
            patients = (ArrayList<Patients>) oStream.readObject();

            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Error:" + e);
        }
    }

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient to remove");
        } else {
            String SearchTerm = ppsnTf.getText();
            boolean found = false;
            for (int i = 0; i < patients.size(); i++) {
                Patients p = patients.get(i);

                if (p.getPpsn().equalsIgnoreCase(SearchTerm)) {

                    patients.remove(p);
                    found = true;
                    break;

                }

            }
            if (!found) {
                JOptionPane.showMessageDialog(null, "No patient found with PPSN: " + SearchTerm);
            }

        }
        clearFields();
        save();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        MenuGUI myGUI = new MenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JPanel bgpatientsJpan;
    private javax.swing.JLabel bloodPLbl;
    private javax.swing.JTextField bloodPTf;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel concentLbl;
    private javax.swing.JTextField concentTf;
    private javax.swing.JRadioButton criticalPatientsRb;
    private javax.swing.JButton displayBtn;
    private javax.swing.JPanel formJpan;
    private javax.swing.JLabel formTitleLbl;
    private javax.swing.JLabel guardNamLbl;
    private javax.swing.JTextField guardNamTf;
    private javax.swing.JLabel injurTypeLbl;
    private javax.swing.JTextField injurTypeTf;
    private javax.swing.JRadioButton injuredPatientsRb;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel operationLbl;
    private javax.swing.JTextField operationTf;
    private javax.swing.JRadioButton ordinaryPatientsRb;
    private javax.swing.JLabel pTypeLbl;
    private javax.swing.JLabel ppsnLbl;
    private javax.swing.JTextField ppsnTf;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel searchAndRemoveAlertLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel symDurationLbl;
    private javax.swing.JTextField symDurationTf;
    private javax.swing.JLabel symptomsLbl;
    private javax.swing.JTextField symptomsTf;
    // End of variables declaration//GEN-END:variables
}
